# Generated by Django 4.2.1 on 2023-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_users"),
        ("users", "0003_user_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="books",
            field=models.ManyToManyField(related_name="followers", to="books.book"),
        ),
    ]
