# Generated by Django 4.2.1 on 2023-05-10 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="users",
            field=models.ManyToManyField(
                related_name="books_following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
