# Generated by Django 4.2.1 on 2023-05-06 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_book_author_book_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="users",
            field=models.ManyToManyField(
                related_name="books_following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
