# Generated by Django 4.2.1 on 2023-05-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="return_date",
        ),
        migrations.AddField(
            model_name="loan",
            name="is_rented",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="returned",
            field=models.BooleanField(default=True),
        ),
    ]
