# Generated by Django 4.2.1 on 2023-05-10 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_remove_loan_return_date_loan_is_rented_loan_returned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="is_rented",
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
