# Generated by Django 4.2.1 on 2023-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0004_remove_loan_is_rented_loan_loan_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
