# Generated by Django 4.2.1 on 2023-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Copy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_rented", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
