# Generated by Django 4.2.1 on 2023-05-08 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_copy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copy",
            name="author",
        ),
        migrations.RemoveField(
            model_name="copy",
            name="name",
        ),
    ]
