# Generated by Django 4.2.1 on 2023-05-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("book_copy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copys",
                to="books.book",
            ),
        ),
    ]
