# Generated by Django 4.2.1 on 2023-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_copy", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="is_rented",
            field=models.BooleanField(default=False),
        ),
    ]
