# Generated by Django 4.2.1 on 2023-05-05 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("following", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MovieOrder",
            new_name="Follow",
        ),
    ]
